"""
models/schemas.py
─────────────────
All Pydantic v2 models for request/response validation.
"""

from pydantic import BaseModel, Field, field_validator
from typing import Optional, Literal
from enum import Enum


# ─── Enums ───────────────────────────────────────────────────────────────────

class Sex(str, Enum):
    male = "Male"
    female = "Female"
    other = "Other"

class SeverityLevel(str, Enum):
    low = "low"
    moderate = "moderate"
    high = "high"
    critical = "critical"

class AgentStatus(str, Enum):
    parsing = "parsing_symptoms"
    retrieving = "retrieving_evidence"
    diagnosing = "generating_diagnosis"
    tracing = "building_reasoning_trace"
    complete = "complete"
    error = "error"


# ─── Input Schemas ───────────────────────────────────────────────────────────

class VitalSigns(BaseModel):
    blood_pressure_systolic: Optional[int] = Field(None, ge=50, le=300)
    blood_pressure_diastolic: Optional[int] = Field(None, ge=30, le=200)
    heart_rate: Optional[int] = Field(None, ge=20, le=300)
    respiratory_rate: Optional[int] = Field(None, ge=4, le=60)
    temperature_celsius: Optional[float] = Field(None, ge=30.0, le=45.0)
    spo2_percent: Optional[float] = Field(None, ge=50.0, le=100.0)
    weight_kg: Optional[float] = Field(None, ge=1.0, le=500.0)


class PatientInput(BaseModel):
    """Primary input for the diagnosis endpoint."""

    # Demographics
    age: int = Field(..., ge=0, le=120, description="Patient age in years")
    sex: Sex = Field(..., description="Biological sex")

    # Clinical info
    chief_complaint: str = Field(..., min_length=5, max_length=500)
    symptoms: str = Field(..., min_length=10, max_length=3000,
                          description="Detailed symptom description with duration/onset")
    vitals: Optional[VitalSigns] = None
    vitals_raw: Optional[str] = Field(None, max_length=500,
                                      description="Raw vitals string if structured not available")

    # History
    medical_history: Optional[str] = Field(None, max_length=3000)
    medications: Optional[str] = Field(None, max_length=1500)
    allergies: Optional[str] = Field(None, max_length=500)
    family_history: Optional[str] = Field(None, max_length=1000)

    # Settings
    max_diagnoses: int = Field(3, ge=1, le=6)
    include_rare: bool = Field(False, description="Include rare/unlikely differentials")

    @field_validator("symptoms")
    @classmethod
    def symptoms_not_pii(cls, v: str) -> str:
        # Basic check — in production add proper de-identification
        if len(v.split()) < 3:
            raise ValueError("Symptoms description too brief — please provide more detail.")
        return v


# ─── Output Schemas ──────────────────────────────────────────────────────────

class ResearchPaper(BaseModel):
    title: str
    journal: str
    year: int
    pmid: str
    relevance_score: float = Field(..., ge=0.0, le=1.0)
    abstract_snippet: str
    pubmed_url: str


class ReasoningStep(BaseModel):
    step_number: int
    clinical_finding: str        # The symptom/sign being reasoned about
    inference: str               # What the AI inferred from it
    supporting_evidence: str     # Which paper/guideline supports this
    confidence_contribution: float  # How much this step adds to overall confidence


class DiagnosisResult(BaseModel):
    rank: int
    condition: str
    icd10_code: str
    confidence_score: float = Field(..., ge=0.0, le=1.0)
    severity: SeverityLevel
    reasoning_trace: list[ReasoningStep]
    supporting_papers: list[ResearchPaper]
    recommended_workup: list[str]    # Tests, imaging to confirm
    treatment_considerations: list[str]
    red_flags: list[str]             # Urgent signs to watch for
    differential_rationale: str      # Why this ranked above/below others


class DiagnosisResponse(BaseModel):
    """Full response from the /diagnose endpoint."""
    session_id: str
    patient_summary: str             # AI-generated 1-paragraph summary
    diagnoses: list[DiagnosisResult]
    total_papers_retrieved: int
    agent_reasoning_summary: str     # High-level explanation of AI's approach
    guardrail_flags: list[str]       # Any safety flags raised
    disclaimer: str = (
        "This output is generated by an AI system for educational and research "
        "purposes only. It is NOT a substitute for clinical judgment, physical "
        "examination, or professional medical advice. Always consult a licensed "
        "healthcare provider for diagnosis and treatment decisions."
    )
    processing_time_seconds: float


class HealthResponse(BaseModel):
    status: str
    vector_db_documents: int
    llm_provider: str
    embedding_model: str


class IngestResponse(BaseModel):
    status: str
    papers_ingested: int
    collection_size: int
    topics_covered: list[str]
